apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: helper
  labels:
    app: helper
spec:
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: helper
        tier: compute
    spec:
      containers:
      - image: profavor/helper:1.0
        imagePullPolicy: Always
        name: helper
        ports:
        - containerPort: 3000 
        volumeMounts:
        - name: timezone-config
          mountPath: /etc/localtime
      volumes:
      - name: timezone-config
        hostPath:
          path: /usr/share/zoneinfo/Asia/Seoul