apiVersion: v1
kind: Secret
metadata:
  name: m-scheduler-secret
type: Opaque
data:
  db-host: null
  db-port: null
  db-schema: null
  db-username: null
  db-password: null
  mail-username: null
  mail-password: null   